export const data = {
  nodes: [
    { index: 1, name: "Name 1" },
    { index: 2, name: "Name 2" },
    { index: 3, name: "Name 3" },
    { index: 4, name: "Name 4" },
    { index: 5, name: "Name 5" },
    { index: 6, name: "Name 6" },
    { index: 7, name: "Name 7" },
    { index: 8, name: "Name 8" },
    { index: 9, name: "Name 9" },
    { index: 10, name: "Name 10" },
  ],
  links: [
    { source: 1, target: 2 },
    { source: 1, target: 3 },
    { source: 1, target: 4 },
    { source: 2, target: 5 },
    { source: 2, target: 6 },
    { source: 3, target: 7 },
    { source: 3, target: 8 },
    { source: 4, target: 9 },
    { source: 4, target: 10 },
    { source: 5, target: 11 },
    { source: 5, target: 1 },
    { source: 6, target: 1 },
    { source: 6, target: 4 },
    { source: 7, target: 5 },
    { source: 7, target: 6 },
    { source: 8, target: 7 },
    { source: 8, target: 8 },
    { source: 9, target: 9 },
    { source: 9, target: 2 },
  ],
};
